name: Run Price Tracker

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  run-price-tracker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium beautifulsoup4

    - name: Set up Google Chrome
      uses: browser-actions/setup-chrome@v3
      with:
        chrome-version: 'latest'  # You can specify a specific version if needed

    - name: Set up ChromeDriver
      uses: actions/setup-chromedriver@v2
      with:
        chrome-version: 'latest'  # This should match the version of Chrome used

    - name: Run price tracker
      env:
        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
      run: python price_tracker.py
