name: Price Tracker

on:
  push:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
name: Price Tracker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:name: Run Price Tracker

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Allows manual trigger from GitHub UI

jobs:
  run-price-tracker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium
        pip install beautifulsoup4

    - name: Install Firefox and Geckodriver
      run: |
        sudo apt-get update
        sudo apt-get install -y firefox-geckodriver

    - name: Run price tracker
      env:
        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
      run: python price_tracker.py

  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv venv
          .\venv\Scripts\activate
          pip install -r requirements.txt
          pip install webdriver-manager beautifulsoup4

      - name: Set up Chrome
        run: choco install googlechrome --version 114.0.5735.90 --force --params "'/NoDesktopShortcut /NoAutoUpdate'"

      - name: Run script
        run: |
          .\venv\Scripts\activate
          python price_tracker.py
        env:
          FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install selenium webdriver-manager beautifulsoup4
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        sudo apt-get install -y libnss3 libgconf-2-4

    - name: Run script
      env:
        FROM_EMAIL: ${{ secrets.FROM_EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        TO_EMAIL: ${{ secrets.TO_EMAIL }}
      run: |
        python price_tracker.py
